# Form implementation generated from reading ui file '/home/charslib/Documents/Core_Program_sc_21/C8_3DViewer_v1.0-1/src/3D_Viewer/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1403, 1025)
        MainWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #606060, stop:0.1 #808080, stop:0.9 #505050, stop:1 #707070);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Setting = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.Setting.setGeometry(QtCore.QRect(10, 3, 321, 991))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        font.setBold(False)
        self.Setting.setFont(font)
        self.Setting.setStyleSheet("border-radius: 40px;\n"
"padding: 0.2em 0.2em 0.3em 0.2em;\n"
"border: 1px solid rgb(100, 100, 100);\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #4c87a1, stop:0.1 rgb(58, 104, 124), stop:1 #2a4b59);\n"
"color: white;")
        self.Setting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Setting.setObjectName("Setting")
        self.open_file = QtWidgets.QPushButton(parent=self.Setting)
        self.open_file.setGeometry(QtCore.QRect(263, 26, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.open_file.setFont(font)
        self.open_file.setAutoFillBackground(False)
        self.open_file.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"\n"
"")
        self.open_file.setIconSize(QtCore.QSize(50, 50))
        self.open_file.setCheckable(True)
        self.open_file.setObjectName("open_file")
        self.path = QtWidgets.QLineEdit(parent=self.Setting)
        self.path.setGeometry(QtCore.QRect(2, 31, 261, 41))
        self.path.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.path.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.path.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.path.setStyleSheet("border: 0px;")
        self.path.setFrame(True)
        self.path.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.path.setClearButtonEnabled(False)
        self.path.setObjectName("path")
        self.download = QtWidgets.QPushButton(parent=self.Setting)
        self.download.setGeometry(QtCore.QRect(0, 74, 127, 41))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(18)
        font.setBold(True)
        self.download.setFont(font)
        self.download.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    padding: 0.2em 0.2em 0.3em 0.2em;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #33ff33, stop:0.1 #00cc00, stop:1 #00e600); \n"
"    color: white;\n"
"}\n"
"QPushButton::hover {\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #00e600, stop:0.1 #009900, stop:1 #00cc00); \n"
"}\n"
"")
        self.download.setObjectName("download")
        self.remove = QtWidgets.QPushButton(parent=self.Setting)
        self.remove.setGeometry(QtCore.QRect(140, 74, 127, 41))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(18)
        font.setBold(True)
        self.remove.setFont(font)
        self.remove.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    padding: 0.2em 0.2em 0.3em 0.2em;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ff3333, stop:0.1 #cc0000, stop:1 #e60000);\n"
"    color: white;\n"
"}\n"
"QPushButton::hover {\n"
"    border: 2px solid rgb(100, 100, 100); \n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #e60000, stop:0.1 #990000, stop:1 #cc0000);\n"
"}")
        self.remove.setObjectName("remove")
        self.groupBox_geometry = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_geometry.setGeometry(QtCore.QRect(0, 133, 321, 32))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        self.groupBox_geometry.setFont(font)
        self.groupBox_geometry.setStyleSheet("background-color: #091114;\n"
"border-radius: 0px;\n"
"")
        self.groupBox_geometry.setTitle("")
        self.groupBox_geometry.setFlat(False)
        self.groupBox_geometry.setCheckable(False)
        self.groupBox_geometry.setObjectName("groupBox_geometry")
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_geometry)
        self.groupBox.setGeometry(QtCore.QRect(0, 31, 321, 111))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.x_rorate_slider = QtWidgets.QSlider(parent=self.groupBox)
        self.x_rorate_slider.setGeometry(QtCore.QRect(30, 20, 221, 25))
        self.x_rorate_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.x_rorate_slider.setMinimum(-360)
        self.x_rorate_slider.setMaximum(360)
        self.x_rorate_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.x_rorate_slider.setObjectName("x_rorate_slider")
        self.y_rorate_slider = QtWidgets.QSlider(parent=self.groupBox)
        self.y_rorate_slider.setGeometry(QtCore.QRect(30, 45, 221, 25))
        self.y_rorate_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.y_rorate_slider.setMinimum(-360)
        self.y_rorate_slider.setMaximum(360)
        self.y_rorate_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.y_rorate_slider.setObjectName("y_rorate_slider")
        self.z_rorate_slider = QtWidgets.QSlider(parent=self.groupBox)
        self.z_rorate_slider.setGeometry(QtCore.QRect(30, 70, 221, 25))
        self.z_rorate_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.z_rorate_slider.setMinimum(-360)
        self.z_rorate_slider.setMaximum(360)
        self.z_rorate_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.z_rorate_slider.setObjectName("z_rorate_slider")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 17, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 43, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0px;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 67, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.x_rorate_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.x_rorate_spin.setGeometry(QtCore.QRect(259, 20, 61, 22))
        self.x_rorate_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.x_rorate_spin.setMinimum(-360.0)
        self.x_rorate_spin.setMaximum(360.0)
        self.x_rorate_spin.setObjectName("x_rorate_spin")
        self.y_rorate_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.y_rorate_spin.setGeometry(QtCore.QRect(259, 45, 61, 22))
        self.y_rorate_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.y_rorate_spin.setMinimum(-360.0)
        self.y_rorate_spin.setMaximum(360.0)
        self.y_rorate_spin.setObjectName("y_rorate_spin")
        self.z_rorate_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.z_rorate_spin.setGeometry(QtCore.QRect(259, 70, 61, 22))
        self.z_rorate_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.z_rorate_spin.setMinimum(-360.0)
        self.z_rorate_spin.setMaximum(360.0)
        self.z_rorate_spin.setObjectName("z_rorate_spin")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_geometry)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 141, 321, 111))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.x_pos_slider = QtWidgets.QSlider(parent=self.groupBox_2)
        self.x_pos_slider.setGeometry(QtCore.QRect(30, 20, 221, 25))
        self.x_pos_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.x_pos_slider.setMinimum(-100)
        self.x_pos_slider.setMaximum(100)
        self.x_pos_slider.setSingleStep(1)
        self.x_pos_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.x_pos_slider.setObjectName("x_pos_slider")
        self.y_pos_slider = QtWidgets.QSlider(parent=self.groupBox_2)
        self.y_pos_slider.setGeometry(QtCore.QRect(30, 45, 221, 25))
        self.y_pos_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.y_pos_slider.setMinimum(-100)
        self.y_pos_slider.setMaximum(100)
        self.y_pos_slider.setSingleStep(1)
        self.y_pos_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.y_pos_slider.setObjectName("y_pos_slider")
        self.z_pos_slider = QtWidgets.QSlider(parent=self.groupBox_2)
        self.z_pos_slider.setGeometry(QtCore.QRect(30, 70, 221, 25))
        self.z_pos_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.z_pos_slider.setMinimum(-100)
        self.z_pos_slider.setMaximum(100)
        self.z_pos_slider.setSingleStep(1)
        self.z_pos_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.z_pos_slider.setObjectName("z_pos_slider")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 18, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 0px;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 44, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 0px;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 69, 21, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 0px;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.z_pos_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.z_pos_spin.setGeometry(QtCore.QRect(259, 70, 61, 22))
        self.z_pos_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.z_pos_spin.setMinimum(-100.0)
        self.z_pos_spin.setMaximum(100.0)
        self.z_pos_spin.setSingleStep(1.0)
        self.z_pos_spin.setObjectName("z_pos_spin")
        self.x_pos_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.x_pos_spin.setGeometry(QtCore.QRect(259, 20, 61, 22))
        self.x_pos_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.x_pos_spin.setMinimum(-100.0)
        self.x_pos_spin.setMaximum(100.0)
        self.x_pos_spin.setSingleStep(1.0)
        self.x_pos_spin.setObjectName("x_pos_spin")
        self.y_pos_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.y_pos_spin.setGeometry(QtCore.QRect(259, 45, 61, 22))
        self.y_pos_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.y_pos_spin.setMinimum(-100.0)
        self.y_pos_spin.setMaximum(100.0)
        self.y_pos_spin.setSingleStep(1.0)
        self.y_pos_spin.setObjectName("y_pos_spin")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_geometry)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 251, 321, 51))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.scale_slider = QtWidgets.QSlider(parent=self.groupBox_4)
        self.scale_slider.setGeometry(QtCore.QRect(30, 20, 221, 25))
        self.scale_slider.setStyleSheet("background: transparent;\n"
"border: 0px;\n"
"color: green;")
        self.scale_slider.setMinimum(10)
        self.scale_slider.setMaximum(500)
        self.scale_slider.setSingleStep(10)
        self.scale_slider.setProperty("value", 100)
        self.scale_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.scale_slider.setObjectName("scale_slider")
        self.scale_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_4)
        self.scale_spin.setGeometry(QtCore.QRect(259, 20, 61, 22))
        self.scale_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.scale_spin.setMinimum(10.0)
        self.scale_spin.setMaximum(500.0)
        self.scale_spin.setSingleStep(10.0)
        self.scale_spin.setObjectName("scale_spin")
        self.pushButton_geometry = QtWidgets.QPushButton(parent=self.groupBox_geometry)
        self.pushButton_geometry.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(False)
        self.pushButton_geometry.setFont(font)
        self.pushButton_geometry.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_geometry.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_geometry.setDefault(False)
        self.pushButton_geometry.setObjectName("pushButton_geometry")
        self.groupBox_color = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_color.setGeometry(QtCore.QRect(0, 165, 321, 32))
        self.groupBox_color.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"border-radius: 0px;")
        self.groupBox_color.setTitle("")
        self.groupBox_color.setObjectName("groupBox_color")
        self.label = QtWidgets.QLabel(parent=self.groupBox_color)
        self.label.setGeometry(QtCore.QRect(10, 43, 101, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_color)
        self.label_2.setGeometry(QtCore.QRect(10, 75, 141, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px;")
        self.label_2.setObjectName("label_2")
        self.pushButton_color = QtWidgets.QPushButton(parent=self.groupBox_color)
        self.pushButton_color.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(True)
        self.pushButton_color.setFont(font)
        self.pushButton_color.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_color.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_color.setDefault(False)
        self.pushButton_color.setObjectName("pushButton_color")
        self.but_color = QtWidgets.QPushButton(parent=self.groupBox_color)
        self.but_color.setGeometry(QtCore.QRect(110, 40, 51, 32))
        self.but_color.setText("")
        self.but_color.setObjectName("but_color")
        self.but_color_back = QtWidgets.QPushButton(parent=self.groupBox_color)
        self.but_color_back.setGeometry(QtCore.QRect(170, 70, 51, 32))
        self.but_color_back.setStyleSheet("background-color: rgb(58, 104, 124);")
        self.but_color_back.setText("")
        self.but_color_back.setObjectName("but_color_back")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_color)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: 0px;")
        self.label_11.setObjectName("label_11")
        self.but_color_ver = QtWidgets.QPushButton(parent=self.groupBox_color)
        self.but_color_ver.setGeometry(QtCore.QRect(130, 110, 51, 32))
        self.but_color_ver.setText("")
        self.but_color_ver.setObjectName("but_color_ver")
        self.groupBox_vertices = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_vertices.setGeometry(QtCore.QRect(0, 197, 321, 32))
        self.groupBox_vertices.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"border-radius: 0px;")
        self.groupBox_vertices.setTitle("")
        self.groupBox_vertices.setObjectName("groupBox_vertices")
        self.radioButton_no = QtWidgets.QRadioButton(parent=self.groupBox_vertices)
        self.radioButton_no.setGeometry(QtCore.QRect(27, 32, 61, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.radioButton_no.setFont(font)
        self.radioButton_no.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.radioButton_no.setStyleSheet("border: 0px;")
        self.radioButton_no.setChecked(True)
        self.radioButton_no.setObjectName("radioButton_no")
        self.radioButton_circle = QtWidgets.QRadioButton(parent=self.groupBox_vertices)
        self.radioButton_circle.setGeometry(QtCore.QRect(117, 33, 71, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.radioButton_circle.setFont(font)
        self.radioButton_circle.setStyleSheet("border: 0px;")
        self.radioButton_circle.setObjectName("radioButton_circle")
        self.radioButton_square = QtWidgets.QRadioButton(parent=self.groupBox_vertices)
        self.radioButton_square.setGeometry(QtCore.QRect(217, 33, 81, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(16)
        self.radioButton_square.setFont(font)
        self.radioButton_square.setStyleSheet("border: 0px;")
        self.radioButton_square.setObjectName("radioButton_square")
        self.pushButton_vertices = QtWidgets.QPushButton(parent=self.groupBox_vertices)
        self.pushButton_vertices.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(True)
        self.pushButton_vertices.setFont(font)
        self.pushButton_vertices.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_vertices.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_vertices.setDefault(False)
        self.pushButton_vertices.setObjectName("pushButton_vertices")
        self.ver_slider = QtWidgets.QSlider(parent=self.groupBox_vertices)
        self.ver_slider.setGeometry(QtCore.QRect(40, 70, 211, 25))
        self.ver_slider.setStyleSheet("border: 0px;")
        self.ver_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ver_slider.setObjectName("ver_slider")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_vertices)
        self.label_9.setGeometry(QtCore.QRect(1, 65, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: 0px;")
        self.label_9.setObjectName("label_9")
        self.ver_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_vertices)
        self.ver_spin.setGeometry(QtCore.QRect(259, 70, 61, 22))
        self.ver_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.ver_spin.setObjectName("ver_spin")
        self.groupBox_edges = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_edges.setGeometry(QtCore.QRect(0, 229, 321, 32))
        self.groupBox_edges.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"border-radius: 0px;")
        self.groupBox_edges.setTitle("")
        self.groupBox_edges.setObjectName("groupBox_edges")
        self.radioButton_solid = QtWidgets.QRadioButton(parent=self.groupBox_edges)
        self.radioButton_solid.setGeometry(QtCore.QRect(60, 32, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_solid.setFont(font)
        self.radioButton_solid.setStyleSheet("border:0px;")
        self.radioButton_solid.setChecked(True)
        self.radioButton_solid.setObjectName("radioButton_solid")
        self.radioButton_dashes = QtWidgets.QRadioButton(parent=self.groupBox_edges)
        self.radioButton_dashes.setGeometry(QtCore.QRect(180, 32, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_dashes.setFont(font)
        self.radioButton_dashes.setStyleSheet("border:0px;")
        self.radioButton_dashes.setObjectName("radioButton_dashes")
        self.pushButton_edges = QtWidgets.QPushButton(parent=self.groupBox_edges)
        self.pushButton_edges.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(True)
        self.pushButton_edges.setFont(font)
        self.pushButton_edges.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_edges.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_edges.setDefault(False)
        self.pushButton_edges.setObjectName("pushButton_edges")
        self.ed_slider = QtWidgets.QSlider(parent=self.groupBox_edges)
        self.ed_slider.setGeometry(QtCore.QRect(40, 70, 211, 25))
        self.ed_slider.setStyleSheet("border: 0px;")
        self.ed_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ed_slider.setObjectName("ed_slider")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_edges)
        self.label_10.setGeometry(QtCore.QRect(1, 65, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: 0px;")
        self.label_10.setObjectName("label_10")
        self.ed_spin = QtWidgets.QDoubleSpinBox(parent=self.groupBox_edges)
        self.ed_spin.setGeometry(QtCore.QRect(259, 70, 61, 22))
        self.ed_spin.setStyleSheet("QDoubleSpinBox {\n"
"border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background: #757476;\n"
"    color: black;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #757476, stop: 1 #5E5E5F);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    width: 12px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background: #5E5E5F;\n"
"    border: 1px solid black;\n"
"}")
        self.ed_spin.setObjectName("ed_spin")
        self.groupBox_project = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_project.setGeometry(QtCore.QRect(0, 261, 321, 32))
        self.groupBox_project.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"border-radius: 0px;")
        self.groupBox_project.setTitle("")
        self.groupBox_project.setObjectName("groupBox_project")
        self.pushButton_project = QtWidgets.QPushButton(parent=self.groupBox_project)
        self.pushButton_project.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(True)
        self.pushButton_project.setFont(font)
        self.pushButton_project.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_project.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_project.setDefault(False)
        self.pushButton_project.setObjectName("pushButton_project")
        self.radioButton_central = QtWidgets.QRadioButton(parent=self.groupBox_project)
        self.radioButton_central.setGeometry(QtCore.QRect(20, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_central.setFont(font)
        self.radioButton_central.setStyleSheet("border:0px;")
        self.radioButton_central.setObjectName("radioButton_central")
        self.radioButton_ortho = QtWidgets.QRadioButton(parent=self.groupBox_project)
        self.radioButton_ortho.setGeometry(QtCore.QRect(180, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_ortho.setFont(font)
        self.radioButton_ortho.setStyleSheet("border:0px;")
        self.radioButton_ortho.setChecked(True)
        self.radioButton_ortho.setObjectName("radioButton_ortho")
        self.groupBox_save = QtWidgets.QGroupBox(parent=self.Setting)
        self.groupBox_save.setGeometry(QtCore.QRect(0, 293, 321, 32))
        self.groupBox_save.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2a4b59, stop:0.1 #2a4b59, stop:1 #2a4b59);\n"
"border-radius: 0px;")
        self.groupBox_save.setTitle("")
        self.groupBox_save.setObjectName("groupBox_save")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.groupBox_save)
        self.pushButton_save.setGeometry(QtCore.QRect(0, 0, 321, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(18)
        font.setBold(True)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"background-color: #4c87a1;\n"
"text-align: left;\n"
"}\n"
"QPushButton::hover {\n"
"background-color:  #2a4b59;\n"
"}")
        self.pushButton_save.setDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.make_jpeg = QtWidgets.QPushButton(parent=self.groupBox_save)
        self.make_jpeg.setGeometry(QtCore.QRect(26, 40, 71, 32))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(14)
        font.setBold(True)
        self.make_jpeg.setFont(font)
        self.make_jpeg.setStyleSheet("QPushButton {\n"
"    padding: 0.2em 0.2em 0.3em 0.2em;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #aaaaaa, stop:0.1 #888888, stop:1 #999999); \n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #999999, stop:0.1 #777777, stop:1 #888888); \n"
"}\n"
"")
        self.make_jpeg.setObjectName("make_jpeg")
        self.make_bmp = QtWidgets.QPushButton(parent=self.groupBox_save)
        self.make_bmp.setGeometry(QtCore.QRect(124, 40, 71, 32))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(14)
        font.setBold(True)
        self.make_bmp.setFont(font)
        self.make_bmp.setStyleSheet("QPushButton {\n"
"    padding: 0.2em 0.2em 0.3em 0.2em;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #aaaaaa, stop:0.1 #888888, stop:1 #999999); \n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #999999, stop:0.1 #777777, stop:1 #888888); \n"
"}\n"
"")
        self.make_bmp.setObjectName("make_bmp")
        self.make_gif = QtWidgets.QPushButton(parent=self.groupBox_save)
        self.make_gif.setGeometry(QtCore.QRect(221, 40, 71, 32))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(14)
        font.setBold(True)
        self.make_gif.setFont(font)
        self.make_gif.setStyleSheet("QPushButton {\n"
"    padding: 0.2em 0.2em 0.3em 0.2em;\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #aaaaaa, stop:0.1 #888888, stop:1 #999999); \n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #999999, stop:0.1 #777777, stop:1 #888888);\n"
"}")
        self.make_gif.setObjectName("make_gif")
        self.open_file.raise_()
        self.path.raise_()
        self.download.raise_()
        self.remove.raise_()
        self.groupBox_color.raise_()
        self.groupBox_edges.raise_()
        self.groupBox_project.raise_()
        self.groupBox_save.raise_()
        self.groupBox_geometry.raise_()
        self.groupBox_vertices.raise_()
        self.view = QtWidgets.QWidget(parent=self.centralwidget)
        self.view.setGeometry(QtCore.QRect(350, 3, 1041, 991))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        self.view.setFont(font)
        self.view.setStyleSheet("border-radius: 40px;\n"
"border: 1px solid rgb(100, 100, 100);\n"
"background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #4c87a1, stop:0.1 rgb(58, 104, 124), stop:1 #2a4b59);")
        self.view.setObjectName("view")
        self.line = QtWidgets.QFrame(parent=self.view)
        self.line.setGeometry(QtCore.QRect(0, 50, 1040, 3))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_23 = QtWidgets.QLabel(parent=self.view)
        self.label_23.setGeometry(QtCore.QRect(500, 1, 51, 31))
        font = QtGui.QFont()
        font.setFamily("AppleGothic")
        font.setPointSize(20)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background: transparent; border: 0; color:white;")
        self.label_23.setObjectName("label_23")
        self.openGLWidget = glView(parent=self.view)
        self.openGLWidget.setGeometry(QtCore.QRect(1, 52, 1039, 891))
        self.openGLWidget.setStyleSheet("")
        self.openGLWidget.setObjectName("openGLWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1403, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Setting.setTitle(_translate("MainWindow", "Setting"))
        self.open_file.setText(_translate("MainWindow", "📁"))
        self.download.setText(_translate("MainWindow", "Download"))
        self.remove.setText(_translate("MainWindow", "Remove"))
        self.groupBox.setTitle(_translate("MainWindow", "Rotate"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Position"))
        self.label_6.setText(_translate("MainWindow", "X"))
        self.label_7.setText(_translate("MainWindow", "Y"))
        self.label_8.setText(_translate("MainWindow", "Z"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Scale"))
        self.pushButton_geometry.setText(_translate("MainWindow", "▶ Geometry"))
        self.label.setText(_translate("MainWindow", "Model color"))
        self.label_2.setText(_translate("MainWindow", "Background color"))
        self.pushButton_color.setText(_translate("MainWindow", "▶ Color"))
        self.label_11.setText(_translate("MainWindow", "Vertices color"))
        self.radioButton_no.setText(_translate("MainWindow", "No"))
        self.radioButton_circle.setText(_translate("MainWindow", "Circle"))
        self.radioButton_square.setText(_translate("MainWindow", "Square"))
        self.pushButton_vertices.setText(_translate("MainWindow", "▶ Vertices"))
        self.label_9.setText(_translate("MainWindow", "Size"))
        self.radioButton_solid.setText(_translate("MainWindow", "Solid"))
        self.radioButton_dashes.setText(_translate("MainWindow", "Dashed"))
        self.pushButton_edges.setText(_translate("MainWindow", "▶ Edges"))
        self.label_10.setText(_translate("MainWindow", "Size"))
        self.pushButton_project.setText(_translate("MainWindow", "▶ Projection"))
        self.radioButton_central.setText(_translate("MainWindow", "Perspective"))
        self.radioButton_ortho.setText(_translate("MainWindow", "Orthographic"))
        self.pushButton_save.setText(_translate("MainWindow", "▶ Save"))
        self.make_jpeg.setText(_translate("MainWindow", "JPEG"))
        self.make_bmp.setText(_translate("MainWindow", "BMP"))
        self.make_gif.setText(_translate("MainWindow", "GIF"))
        self.label_23.setText(_translate("MainWindow", "View"))
from glview import glView
